CREATE TABLE HOCKY (
    MaHK INT PRIMARY KEY AUTO_INCREMENT,
    TenHK VARCHAR(50) NOT NULL
);

CREATE TABLE NAMHOC (
    MaNH INT PRIMARY KEY AUTO_INCREMENT,
    Nam1 INT NOT NULL,
    Nam2 INT NOT NULL
);

CREATE TABLE LOAIHINHKIEMTRA (
    MaLHKT INT PRIMARY KEY AUTO_INCREMENT,
    TenLHKT VARCHAR(100) NOT NULL,
    HeSo FLOAT NOT NULL
);

CREATE TABLE KHOILOP (
    MaKL INT PRIMARY KEY AUTO_INCREMENT,
    TenKL VARCHAR(50) NOT NULL
);

CREATE TABLE MONHOC (
    MaMonHoc INT PRIMARY KEY AUTO_INCREMENT,
    TenMonHoc VARCHAR(100) NOT NULL,
    HeSoMon FLOAT NOT NULL
);

CREATE TABLE HOCSINH (
    MaHocSinh INT PRIMARY KEY AUTO_INCREMENT,
    HoTen VARCHAR(100) NOT NULL,
    NgaySinh DATE NOT NULL,
    GioiTinh CHAR(1) NOT NULL,
    DiaChi VARCHAR(255),
    NgayTiepNhan DATE,
    GhiChu VARCHAR(255)
);

CREATE TABLE LOP (
    MaLop INT PRIMARY KEY AUTO_INCREMENT,
    TenLop VARCHAR(50) NOT NULL,
    MaKhoiLop INT NOT NULL,
    MaNamHoc INT NOT NULL,
    SiSo INT
);

CREATE TABLE HOCSINH_LOP (
    MaLop INT NOT NULL,
    MaHocSinh INT NOT NULL,
    MaHocKy INT NOT NULL,
    DiemTBHK FLOAT,
    PRIMARY KEY (MaLop, MaHocSinh, MaHocKy)
);

CREATE TABLE BANGDIEMMON (
    MaBangDiemMon INT PRIMARY KEY AUTO_INCREMENT,
    MaLop INT NOT NULL,
    MaHocKy INT NOT NULL,
    MaMon INT NOT NULL
);

CREATE TABLE CT_BANGDIEMMON_HOCSINH (
    MaCTBangDiemMon INT PRIMARY KEY AUTO_INCREMENT,
    MaBangDiemMon INT NOT NULL,
    MaHocSinh INT NOT NULL,
    DiemTBMon FLOAT
);

CREATE TABLE CT_BANGDIEMMON_LHKT (
    MaCTBangDiemMon INT NOT NULL,
    MaLHKT INT NOT NULL,
    Lan INT NOT NULL,
    Diem FLOAT,
    PRIMARY KEY (MaCTBangDiemMon, MaLHKT, Lan)
);

CREATE TABLE BAOCAOTKMON (
    MaBCTKMon INT PRIMARY KEY AUTO_INCREMENT,
    MaMon INT NOT NULL,
    MaHocKy INT NOT NULL,
    MaNamHoc INT NOT NULL
);

CREATE TABLE CT_BAOCAOTKMON (
    MaBCTKMon INT NOT NULL,
    MaLop INT NOT NULL,
    SoLuongDat INT,
    TiLeDat FLOAT,
    PRIMARY KEY (MaBCTKMon, MaLop)
);

CREATE TABLE BAOCAOTKHK (
    MaHocKy INT NOT NULL,
    MaNamHoc INT NOT NULL,
    MaLop INT NOT NULL,
    SoLuongDat INT,
    TiLeDat FLOAT,
    PRIMARY KEY (MaHocKy, MaNamHoc, MaLop)
);

CREATE TABLE QUYEN (
    MaQuyen INT PRIMARY KEY AUTO_INCREMENT,
    PhanQuyenHeThong TINYINT(1),
    ThayDoiThamSo TINYINT(1),
    ThayDoiQuyDinh TINYINT(1),
    DieuChinhNghiepVu TINYINT(1),
    TraCuuDiemVaLopHoc TINYINT(1),
    TraCuuHocSinh TINYINT(1)
);

CREATE TABLE NHOMNGUOIDUNG (
    MaNhomNguoiDung INT PRIMARY KEY AUTO_INCREMENT,
    TenNhomNguoiDung VARCHAR(100),
    MaQuyen INT NOT NULL
);

CREATE TABLE NGUOIDUNG (
    MaNguoiDung INT PRIMARY KEY AUTO_INCREMENT,
    TenDangNhap VARCHAR(50) UNIQUE NOT NULL,
    MatKhau VARCHAR(255) NOT NULL,
    HoVaTen VARCHAR(100),
    Email VARCHAR(100),
    MaNhomNguoiDung INT NOT NULL
);

CREATE TABLE THAMSO (
    MaThamSo INT PRIMARY KEY AUTO_INCREMENT,
    Tuoi_Toi_Da INT,
    Tuoi_Toi_Thieu INT,
    Si_So_Toi_Da INT,
    Diem_Toi_Thieu INT,
    Diem_Toi_Da INT,
    Diem_Dat_Mon INT,
    Diem_Dat INT,
    MaNamHoc INT NOT NULL
);


ALTER TABLE LOP 
ADD CONSTRAINT fk_LOP_KHOILOP FOREIGN KEY (MaKhoiLop) REFERENCES KHOILOP(MaKL),
ADD CONSTRAINT fk_LOP_NAMHOC FOREIGN KEY (MaNamHoc) REFERENCES NAMHOC(MaNH);

ALTER TABLE HOCSINH_LOP 
ADD CONSTRAINT fk_HSLOP_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
ADD CONSTRAINT fk_HSLOP_HOCSINH FOREIGN KEY (MaHocSinh) REFERENCES HOCSINH(MaHocSinh),
ADD CONSTRAINT fk_HSLOP_HOCKY FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHK);

ALTER TABLE BANGDIEMMON
ADD CONSTRAINT fk_BDM_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop),
ADD CONSTRAINT fk_BDM_HK FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHK),
ADD CONSTRAINT fk_BDM_MON FOREIGN KEY (MaMon) REFERENCES MONHOC(MaMonHoc);

ALTER TABLE CT_BANGDIEMMON_HOCSINH
ADD CONSTRAINT fk_CTBDM_BDM FOREIGN KEY (MaBangDiemMon) REFERENCES BANGDIEMMON(MaBangDiemMon),
ADD CONSTRAINT fk_CTBDM_HS FOREIGN KEY (MaHocSinh) REFERENCES HOCSINH(MaHocSinh);

ALTER TABLE CT_BANGDIEMMON_LHKT
ADD CONSTRAINT fk_CTBDM_LHKT_CT FOREIGN KEY (MaCTBangDiemMon) REFERENCES CT_BANGDIEMMON_HOCSINH(MaCTBangDiemMon),
ADD CONSTRAINT fk_CTBDM_LHKT_LHKT FOREIGN KEY (MaLHKT) REFERENCES LOAIHINHKIEMTRA(MaLHKT);

ALTER TABLE BAOCAOTKMON
ADD CONSTRAINT fk_BCTKM_MON FOREIGN KEY (MaMon) REFERENCES MONHOC(MaMonHoc),
ADD CONSTRAINT fk_BCTKM_HK FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHK),
ADD CONSTRAINT fk_BCTKM_NH FOREIGN KEY (MaNamHoc) REFERENCES NAMHOC(MaNH);

ALTER TABLE CT_BAOCAOTKMON
ADD CONSTRAINT fk_CTBCTKMON_BC FOREIGN KEY (MaBCTKMon) REFERENCES BAOCAOTKMON(MaBCTKMon),
ADD CONSTRAINT fk_CTBCTKMON_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop);

ALTER TABLE BAOCAOTKHK
ADD CONSTRAINT fk_BCTKHK_HK FOREIGN KEY (MaHocKy) REFERENCES HOCKY(MaHK),
ADD CONSTRAINT fk_BCTKHK_NH FOREIGN KEY (MaNamHoc) REFERENCES NAMHOC(MaNH),
ADD CONSTRAINT fk_BCTKHK_LOP FOREIGN KEY (MaLop) REFERENCES LOP(MaLop);

ALTER TABLE NHOMNGUOIDUNG
ADD CONSTRAINT fk_NHOMND_QUYEN FOREIGN KEY (MaQuyen) REFERENCES QUYEN(MaQuyen);

ALTER TABLE NGUOIDUNG
ADD CONSTRAINT fk_ND_NHOMND FOREIGN KEY (MaNhomNguoiDung) REFERENCES NHOMNGUOIDUNG(MaNhomNguoiDung);

ALTER TABLE THAMSO
ADD CONSTRAINT fk_THAMSO_NH FOREIGN KEY (MaNamHoc) REFERENCES NAMHOC(MaNH);

